# Enter your per-environment constants below

development: &default
  host_uri: "localhost:3000"
  blast_job_delay: <%= 5.seconds %>
  default_cache_timeout: <%= 0.minutes %>
  umbrella_user_email_address: "offlinedonations@yourdomain.org"
  send_grid_health_check_uri: "http://sendgrid.com/api/stats.get.json?api_user=<%= ENV["SENDGRID_USERNAME"] %>&api_key=<%= ENV["SENDGRID_PASSWORD"] %>&days=1"
  s3_bucket_uri: "//<%= ENV['S3_BUCKET_NAME'] %>.s3.amazonaws.com"
  enable_unfiltered_blasting: <%= ENV['ENABLE_UNFILTERED_BLASTING'] || false %>
  authenticate_api_calls: <%= ENV["AUTHENTICATE_API_CALLS"] || false %>
  readonly_database_url: <%= ENV["READONLY_DATABASE_URL"] %>
  no_reply_address: <%= ENV["NO_REPLY_ADDRESS"] || "noreply@yourdomain.com" %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  google_maps_js_url: <%= ENV["GOOGLE_MAPS_JS_URL"] || "http://maps.google.com/maps/api/js?sensor=false" %>
  keyed_google_maps_js_url: <%= ENV["KEYED_GOOGLE_MAPS_JS_URL"] || "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&sensor=false" %>

production:
  <<: *default
  default_cache_timeout: <%= 5.minutes %>
  blast_job_delay: <%= 5.minutes %>

test:
  <<: *default
  host_uri: "localhost:3000"
  default_cache_timeout: <%= 5.minutes %>
  blast_job_delay: <%= 0 %>
  send_grid_health_check_uri: ""
  s3_bucket_uri: "//xyz.s3.amazonaws.com"

showcase:
  <<: *default

staging:
  <<: *default
  default_cache_timeout: <%= 5.minutes %>
  blast_job_delay: <%= 1.minute %>
